# Only run this pipeline when manually triggered
trigger: none
pr: none

parameters:
  # Choose a package to publish at the time of job creation
  - name: packageToPublish
    displayName: Package to publish
    type: string
    values:
      - microsoft-vscode-processutils
      - microsoft-vscode-container-client
      - microsoft-vscode-docker-registries
      - microsoft-vscode-inproc-mcp
  # The version to publish--used for ensuring the expected version is published
  - name: publishVersion
    displayName: Version to publish
    type: string
  # Whether to do a dry run (i.e., not actually publish)
  - name: dryRun
    displayName: Dry run
    type: boolean
    default: false

resources:
  pipelines:
    # Reference the build pipeline to get the artifacts
    - pipeline: build # This must be "build"
      source: \Azure Tools\VSCode\Packages\vscode-docker-extensibility # Name of the pipeline that produces the artifacts
  repositories:
    # Use the shared templates from microsoft/vscode-azuretools
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelinesv2_2 # TODO: update to final branch
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Pick up shared AZCode variables
  - template: azdo-pipelines/azcode.variables.yml@azExtTemplates
  - name: TeamName
    value: "Container Tools Team" # Required for MicroBuild signing and telemetry

extends:
  template: azdo-pipelines/1es-mb-release-npm.yml@azExtTemplates # Use the NPM release template
  parameters:
    packageToPublish: ${{ parameters.packageToPublish }}
    publishVersion: ${{ parameters.publishVersion }}
    dryRun: ${{ parameters.dryRun }}
    ownerAliases: ${{ variables.npmReleaseOwnerAliases }}
    approverAliases: ${{ variables.npmReleaseApproverAliases }}
    gitHubServiceConnection: ${{ variables.gitHubServiceConnection }}
    releaseApprovalEnvironment: VSCodeDockerExtensionPublish
