jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: job-steps.yml

  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: job-steps.yml
    variables:
      Codeql.Enabled: $[in(variables['Build.Reason'], 'Manual', 'Schedule')] # Only on scheduled builds because it is slow # TODO: remove manual when verified

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - main

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
    always: false
